const fs = require('fs');
const path = require('path');

const WORKFLOW_PATH = '.github/workflows/ship-it.yml';

/**
 * Check if a GitHub Actions workflow exists. If not, generate one
 * from the template and commit it to the branch.
 */
async function ensureWorkflow({ octokit, owner, repo, branch, devEnv, prodEnv }) {
  const exists = await workflowExists({ octokit, owner, repo, branch });
  if (exists) {
    return { created: false, message: 'You already have automation set up. I\'ll work with what\'s there.' };
  }

  const content = generateWorkflow({ devEnv, prodEnv });
  await commitWorkflow({ octokit, owner, repo, branch, content });

  return { created: true, message: 'I set up a basic automation pipeline for you.' };
}

async function workflowExists({ octokit, owner, repo, branch }) {
  try {
    await octokit.rest.repos.getContent({
      owner, repo, path: '.github/workflows', ref: branch
    });
    return true;
  } catch (error) {
    if (error.status === 404) return false;
    throw error;
  }
}

function generateWorkflow({ devEnv = 'dev', prodEnv = 'production' }) {
  const templatePath = path.join(__dirname, '..', 'templates', 'workflow.yml');
  let template = fs.readFileSync(templatePath, 'utf8');
  template = template.replace(/\{\{DEV_ENV\}\}/g, devEnv);
  template = template.replace(/\{\{PROD_ENV\}\}/g, prodEnv);
  return template;
}

async function commitWorkflow({ octokit, owner, repo, branch, content }) {
  // Get the latest commit SHA on the branch
  const { data: ref } = await octokit.rest.git.getRef({
    owner, repo, ref: `heads/${branch}`
  });
  const latestSHA = ref.object.sha;

  // Get the tree of the latest commit
  const { data: commit } = await octokit.rest.git.getCommit({
    owner, repo, commit_sha: latestSHA
  });

  // Create a blob for the workflow file
  const { data: blob } = await octokit.rest.git.createBlob({
    owner, repo,
    content: Buffer.from(content).toString('base64'),
    encoding: 'base64'
  });

  // Create a new tree with the workflow file added
  const { data: tree } = await octokit.rest.git.createTree({
    owner, repo,
    base_tree: commit.tree.sha,
    tree: [{
      path: WORKFLOW_PATH,
      mode: '100644',
      type: 'blob',
      sha: blob.sha
    }]
  });

  // Create a new commit
  const { data: newCommit } = await octokit.rest.git.createCommit({
    owner, repo,
    message: 'chore: add ship-it CI/CD pipeline\n\nGenerated by /ship-it skill.',
    tree: tree.sha,
    parents: [latestSHA]
  });

  // Update the branch reference
  await octokit.rest.git.updateRef({
    owner, repo,
    ref: `heads/${branch}`,
    sha: newCommit.sha
  });
}

module.exports = { ensureWorkflow };
