const fs = require('fs');
const path = require('path');

const WORKFLOW_PATH = '.github/workflows/ship-it.yml';

/**
 * Check if a GitHub Actions workflow exists. If not, generate one
 * based on the merged config (infra, services, deployment settings).
 */
async function ensureWorkflow({ octokit, owner, repo, branch, config }) {
  const exists = await workflowExists({ octokit, owner, repo, branch });
  if (exists) {
    return { created: false, message: 'You already have automation set up. I\'ll work with what\'s there.' };
  }

  const content = generateWorkflow(config);
  await commitWorkflow({ octokit, owner, repo, branch, content });

  return { created: true, message: 'I set up a deployment pipeline for you.' };
}

async function workflowExists({ octokit, owner, repo, branch }) {
  try {
    await octokit.rest.repos.getContent({
      owner, repo, path: '.github/workflows', ref: branch
    });
    return true;
  } catch (error) {
    if (error.status === 404) return false;
    throw error;
  }
}

/**
 * Generate a workflow based on available config:
 *   - reusable_workflow set  -> thin caller workflow
 *   - infra configured       -> full deploy steps (Docker, ECR/ACR, ECS/AKS)
 *   - infra not configured   -> placeholder deploy steps
 */
function generateWorkflow(config) {
  if (!config) {
    // Fallback: no config at all, use basic template
    return generateBasicWorkflow({ devEnv: 'dev', prodEnv: 'production' });
  }

  // Option 1: Reusable workflow reference
  if (config.deployment.reusableWorkflow) {
    return generateCallerWorkflow(config);
  }

  // Option 2: Full deploy with infra configured
  if (config.infra.configured) {
    if (config.infra.provider === 'aws') {
      return generateAwsWorkflow(config);
    }
    if (config.infra.provider === 'azure') {
      return generateAzureWorkflow(config);
    }
  }

  // Option 3: Placeholder deploy steps
  return generatePendingWorkflow(config);
}

// --- Workflow generators ---

function generateCallerWorkflow(config) {
  const devEnv = config.deployment.environments.dev || 'dev';
  const prodEnv = config.deployment.environments.production || 'production';

  return `# Generated by /ship-it -- references your org's shared pipeline
name: ship-it pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ship-it:
    uses: ${config.deployment.reusableWorkflow}
    with:
      environment-dev: ${devEnv}
      environment-prod: ${prodEnv}
    secrets: inherit
`;
}

function generateAwsWorkflow(config) {
  const aws = config.infra.aws || {};
  const devEnv = config.deployment.environments.dev || 'dev';
  const prodEnv = config.deployment.environments.production || 'production';
  const region = aws.region || 'us-east-1';
  const registry = aws.ecr_registry || `${aws.account_id}.dkr.ecr.${region}.amazonaws.com`;
  const cluster = aws.ecs?.cluster_name || '';
  const slug = config.app.slug || 'app';
  const services = config.app.services || [];

  // Build steps for each service
  const buildSteps = services.map(svc => `
      - name: Build ${svc.name} image
        run: |
          docker build -t ${registry}/${slug}-${svc.name}:$\{{ github.sha }} \\
            -f ${svc.dockerfile} .

      - name: Push ${svc.name} image
        run: |
          docker push ${registry}/${slug}-${svc.name}:$\{{ github.sha }}`
  ).join('\n');

  const deploySteps = services.map(svc => `
      - name: Deploy ${svc.name}
        run: |
          aws ecs update-service \\
            --cluster ${cluster} \\
            --service ${slug}-${svc.name}-$\{{ matrix.env }} \\
            --force-new-deployment \\
            --region ${region}`
  ).join('\n');

  const healthSteps = services.filter(s => s.healthCheck).map(svc => `
      - name: Verify ${svc.name} health
        run: |
          echo "Waiting for ${svc.name} to be healthy..."
          # Health check verification handled by ECS service health check`
  ).join('\n');

  return `# Generated by /ship-it -- AWS ECS/Fargate deployment
name: ship-it pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  AWS_REGION: ${region}
  ECR_REGISTRY: ${registry}
  ECS_CLUSTER: ${cluster}

jobs:
  build-and-validate:
    name: Build & Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: $\{{ secrets.AWS_ROLE_ARN }}
          aws-region: ${region}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Lint
        run: echo "Add your lint command here"
        continue-on-error: $\{{ !contains(github.event.pull_request.labels.*.name, 'intent:prod-ready') }}

      - name: Security scan
        run: echo "Add your security scan here"
        continue-on-error: $\{{ !contains(github.event.pull_request.labels.*.name, 'intent:prod-ready') }}
${buildSteps}

  deploy-dev:
    name: Deploy to Dev
    needs: build-and-validate
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: ${devEnv}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: $\{{ secrets.AWS_ROLE_ARN }}
          aws-region: ${region}
${deploySteps}
${healthSteps}

  deploy-prod:
    name: Deploy to Production
    needs: deploy-dev
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: ${prodEnv}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: $\{{ secrets.AWS_ROLE_ARN }}
          aws-region: ${region}
${deploySteps}
${healthSteps}
`;
}

function generateAzureWorkflow(config) {
  const azure = config.infra.azure || {};
  const devEnv = config.deployment.environments.dev || 'dev';
  const prodEnv = config.deployment.environments.production || 'production';
  const acrLogin = azure.acr_login_server || `${azure.acr_name}.azurecr.io`;
  const aksCluster = azure.aks?.cluster_name || '';
  const aksRg = azure.aks?.resource_group || '';
  const slug = config.app.slug || 'app';
  const services = config.app.services || [];

  const buildSteps = services.map(svc => `
      - name: Build ${svc.name} image
        run: |
          docker build -t ${acrLogin}/${slug}-${svc.name}:$\{{ github.sha }} \\
            -f ${svc.dockerfile} .

      - name: Push ${svc.name} image
        run: |
          docker push ${acrLogin}/${slug}-${svc.name}:$\{{ github.sha }}`
  ).join('\n');

  const deploySteps = services.map(svc => `
      - name: Deploy ${svc.name}
        run: |
          kubectl set image deployment/${slug}-${svc.name} \\
            ${svc.name}=${acrLogin}/${slug}-${svc.name}:$\{{ github.sha }} \\
            -n $\{{ matrix.namespace }}`
  ).join('\n');

  return `# Generated by /ship-it -- Azure AKS deployment
name: ship-it pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  ACR_LOGIN_SERVER: ${acrLogin}
  AKS_CLUSTER: ${aksCluster}
  AKS_RESOURCE_GROUP: ${aksRg}

jobs:
  build-and-validate:
    name: Build & Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: $\{{ secrets.AZURE_CLIENT_ID }}
          tenant-id: $\{{ secrets.AZURE_TENANT_ID }}
          subscription-id: $\{{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name ${azure.acr_name || 'your-acr'}

      - name: Lint
        run: echo "Add your lint command here"
        continue-on-error: $\{{ !contains(github.event.pull_request.labels.*.name, 'intent:prod-ready') }}

      - name: Security scan
        run: echo "Add your security scan here"
        continue-on-error: $\{{ !contains(github.event.pull_request.labels.*.name, 'intent:prod-ready') }}
${buildSteps}

  deploy-dev:
    name: Deploy to Dev
    needs: build-and-validate
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: ${devEnv}
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: $\{{ secrets.AZURE_CLIENT_ID }}
          tenant-id: $\{{ secrets.AZURE_TENANT_ID }}
          subscription-id: $\{{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${aksRg} --name ${aksCluster}
${deploySteps}

  deploy-prod:
    name: Deploy to Production
    needs: deploy-dev
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: ${prodEnv}
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: $\{{ secrets.AZURE_CLIENT_ID }}
          tenant-id: $\{{ secrets.AZURE_TENANT_ID }}
          subscription-id: $\{{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${aksRg} --name ${aksCluster}
${deploySteps}
`;
}

function generatePendingWorkflow(config) {
  const devEnv = config?.deployment?.environments?.dev || 'dev';
  const prodEnv = config?.deployment?.environments?.production || 'production';

  return `# Generated by /ship-it
# Deployment steps are placeholders -- fill in the infra section of .ship-it.yml
# to generate real deployment steps.
# See: https://github.com/sealmindset/ship-it/blob/main/docs/devops-guide.md
name: ship-it pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-validate:
    name: Build & Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo "Add your build command here"

      - name: Lint
        run: echo "Add your lint command here"
        continue-on-error: $\{{ !contains(github.event.pull_request.labels.*.name, 'intent:prod-ready') }}

      - name: Security scan
        run: echo "Add your security scan here"
        continue-on-error: $\{{ !contains(github.event.pull_request.labels.*.name, 'intent:prod-ready') }}

  deploy-dev:
    name: Deploy to Dev
    needs: build-and-validate
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: ${devEnv}
    steps:
      - uses: actions/checkout@v4

      # TODO: DevOps -- fill in the infra section of .ship-it.yml
      # Once configured, /ship-it will generate real deployment steps
      - name: Deploy to dev
        run: |
          echo "Deployment pending -- DevOps infrastructure not yet configured"
          echo "Fill in the infra section of .ship-it.yml to enable deployment"

  deploy-prod:
    name: Deploy to Production
    needs: deploy-dev
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: ${prodEnv}
    steps:
      - uses: actions/checkout@v4

      # TODO: DevOps -- fill in the infra section of .ship-it.yml
      - name: Deploy to production
        run: |
          echo "Deployment pending -- DevOps infrastructure not yet configured"
          echo "Fill in the infra section of .ship-it.yml to enable deployment"
`;
}

/**
 * Basic workflow fallback -- no config available at all.
 * Uses the static template file.
 */
function generateBasicWorkflow({ devEnv = 'dev', prodEnv = 'production' }) {
  const templatePath = path.join(__dirname, '..', 'templates', 'workflow.yml');
  let template = fs.readFileSync(templatePath, 'utf8');
  template = template.replace(/\{\{BUILD_CMD\}\}/g, 'echo "Add your build command here"');
  template = template.replace(/\{\{LINT_CMD\}\}/g, 'echo "Add your lint command here"');
  template = template.replace(/\{\{SECURITY_CMD\}\}/g, 'echo "Add your security scan here"');
  template = template.replace(/\{\{DEV_ENV\}\}/g, devEnv);
  template = template.replace(/\{\{PROD_ENV\}\}/g, prodEnv);
  return template;
}

async function commitWorkflow({ octokit, owner, repo, branch, content }) {
  const { data: ref } = await octokit.rest.git.getRef({
    owner, repo, ref: `heads/${branch}`
  });
  const latestSHA = ref.object.sha;

  const { data: commit } = await octokit.rest.git.getCommit({
    owner, repo, commit_sha: latestSHA
  });

  const { data: blob } = await octokit.rest.git.createBlob({
    owner, repo,
    content: Buffer.from(content).toString('base64'),
    encoding: 'base64'
  });

  const { data: tree } = await octokit.rest.git.createTree({
    owner, repo,
    base_tree: commit.tree.sha,
    tree: [{
      path: WORKFLOW_PATH,
      mode: '100644',
      type: 'blob',
      sha: blob.sha
    }]
  });

  const { data: newCommit } = await octokit.rest.git.createCommit({
    owner, repo,
    message: 'chore: add ship-it CI/CD pipeline\n\nGenerated by /ship-it skill.',
    tree: tree.sha,
    parents: [latestSHA]
  });

  await octokit.rest.git.updateRef({
    owner, repo,
    ref: `heads/${branch}`,
    sha: newCommit.sha
  });
}

module.exports = { ensureWorkflow, generateWorkflow };
